import { navbar } from "./navbar.js";

// Render the navbar
document.addEventListener("DOMContentLoaded", () => {
  const navbarContainer = document.querySelector("Header"); // Ensure you have a container with this ID in your HTML
  if (navbarContainer) {
    navbarContainer.innerHTML = navbar(); // Append the HTML generated by the navbar function
  } else {
    console.error("Navbar container element not found");
  }

  // Now attach your event listeners
  const menuItems = document.querySelectorAll(".menu-item");
  const dropdown = document.querySelector(".dropdown");

  if (!dropdown) {
    console.error("Dropdown element not found in the DOM");
    return; // Prevent further execution if dropdown is missing
  }

  let timeout; // To track the timeout for hiding
  menuItems.forEach((menuItem) => {
    menuItem.addEventListener("mouseover", () => {
      clearTimeout(timeout); // Cancel any previous hide timeout
      dropdown.classList.add("show");
      dropdown.style.display = "block"; // Ensure dropdown is visible
    });

    menuItem.addEventListener("mouseout", () => {
      timeout = setTimeout(() => {
        dropdown.classList.remove("show");
        dropdown.style.display = "none";
      }, 200); // Small delay to allow hover on dropdown
    });
  });

  dropdown.addEventListener("mouseover", () => {
    clearTimeout(timeout); // Cancel hide timeout when hovering over dropdown
    dropdown.classList.add("show");
    dropdown.style.display = "block";
  });

  dropdown.addEventListener("mouseout", () => {
    timeout = setTimeout(() => {
      dropdown.classList.remove("show");
      dropdown.style.display = "none";
    }, 200); // Small delay before hiding
  });
});
